#!/bin/bash
full_dir=`cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P`
full_0="${full_dir}/`basename $0`"
full_gs_ls="${full_dir}/gs-ls"

git_svn_clone_children() {
	sh $full_gs_ls | 
		while read line; do 
			# ls_git_svn_externals.sh gives "SUB_DIR REPO_URL CLONE_DIR CLONE_FULL_DIR"
			words=(${line})
			repo_r=${words[1]}
			clone_dir_r=${words[3]}
			
			eval "$full_0 $repo_r $clone_dir_r"
		done
}

if [[ $1 ]] && [[ $2 ]]; then 
	repo_url=$1
	clone_dir=$2
	git svn clone $repo_url $clone_dir || exit
	pushd $clone_dir> /dev/null
	echo "> cd into ${clone_dir} from `pwd`"
		git_svn_clone_children
	popd > /dev/null
	echo "< cd back to `pwd` from ${clone_dir}"

elif [[ $1 ]]; then
	echo "Usage: gs-clone REPO_URL CLONE_DIR or gs-clone to only clone externals"
	exit;
else
	git_svn_clone_children
fi
