#!/bin/bash
full_dir=`cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P`
full_gs_clone="${full_dir}/gs-clone"

if [[ $1 ]] && [[ $2 ]]; then 
	ref_clone_dir=$1
	repo_url=`gs-url $ref_clone_dir`
	clone_dir=$2
	eval "$full_gs_clone $repo_url $clone_dir"
else
	echo "Usage: gs-copy REF_COPY_DIR CLONE_DIR"
	echo "Underlying:"
	echo "  URL <- \`gs-url REF_COPY_DIR\`"
	echo "  gs-clone \$URL \$CLONE_DIR"
fi
