#!/bin/bash
full_dir=`cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P`
full_gs_splitext="${full_dir}/gs-splitext"

if [ -z $1 ]; then 
	git svn show-externals | sh $full_gs_splitext
elif [[ $1 =~ ^[0-9] ]]; then
	git svn show-externals | sh $full_gs_splitext | cut -d ' ' -f $1
fi

